/* Espanol.
 *
 * Les cles sont les textes francais tels qu'ils sont ecrits dans les sources.
 * Un texte absent d'ici passe par l'anglais avant de retomber sur le francais.
 * Voir `src/i18n.js`.
 *
 * Ne PAS traduire : les noms de pieces, d'appareils et d'entites — ils viennent
 * de Home Assistant, deja dans la langue de l'installation.
 */
export default {
  // Navigation et vues
  'MAISON': 'CASA',
  'SYSTÈME': 'SISTEMA',
  'VUES SECONDAIRES': 'VISTAS SECUNDARIAS',
  'APPAREILS EN LIGNE': 'DISPOSITIVOS EN LÍNEA',
  'HORS LIGNE': 'SIN CONEXIÓN',
  'CONNEXION…': 'CONECTANDO…',
  'Objets': 'Dispositivos',
  'Climat': 'Climatización',
  'Volets': 'Persianas',
  'Aspirateur': 'Aspiradora',
  'Croquettes': 'Pienso',
  'Alarme désarmée': 'Alarma desarmada',
  'Alarme armée': 'Alarma armada',
  'Alarme déclenchée': 'Alarma activada',
  'En ligne': 'En línea',
  'Vues secondaires': 'Vistas secundarias',
  'Accueil': 'Inicio',
  'Pièces': 'Áreas',
  'Pièce': 'Área',
  'Scènes': 'Escenas',
  'Scènes rapides': 'Escenas rápidas',
  'Objets connectés': 'Dispositivos conectados',
  'Énergie': 'Energía',
  'Sécurité': 'Seguridad',
  'Système': 'Sistema',
  'Météo': 'Clima',
  'Lumières': 'Luces',
  'Médias': 'Multimedia',
  'Média': 'Multimedia',
  'Caméras': 'Cámaras',
  'Caméra': 'Cámara',
  'Paramètres': 'Ajustes',
  'Réseau': 'Red',
  'Identité': 'Identidad',
  'Présence': 'Presencia',

  // Textes construits
  '{n} lampes allumées': '{n} luces encendidas',
  '{n} lampe allumée': '{n} luz encendida',
  'Tout éteint': 'Todo apagado',
  'Dans {j}j': 'En {j} d',
  'IMPORT RÉSEAU': 'IMPORTACIÓN DE RED',
  'EXPORT RÉSEAU': 'EXPORTACIÓN A RED',
  'QUALITÉ AIR': 'CALIDAD DEL AIRE',
  'BON': 'BUENA',
  'MOYEN': 'REGULAR',
  'ÉLEVÉ': 'ALTA',
  'prés.': 'presentes',
  'En cours': 'En curso',
  'Volets, robots et sécurité': 'Persianas, robots y seguridad',
  'TOUT AU REPOS': 'TODO EN REPOSO',
  'ACTIF': 'ACTIVO',
  'ACTIFS': 'ACTIVOS',
  'caméras en ligne': 'cámaras en línea',
  'Armée': 'Armada',
  'Désarmée': 'Desarmada',
  'Home Assistant · En ligne': 'Home Assistant · En línea',
  'Home Assistant · Hors ligne': 'Home Assistant · Sin conexión',
  '{n} pièces': '{n} áreas',
  '{n} pièce': '{n} área',
  '{n} en ligne': '{n} en línea',
  '{n} caméras': '{n} cámaras',
  '{n} sur {t} allumées': '{n} de {t} encendidas',
  '{n} pièces sélectionnées': '{n} áreas seleccionadas',
  '{n} pièce sélectionnée': '{n} área seleccionada',
  'Nettoyer {n} pièces': 'Limpiar {n} áreas',
  'Nettoyer {n} pièce': 'Limpiar {n} área',
  'Sélectionne des pièces': 'Selecciona áreas',
  'passage complet': 'pasada completa',
  'Rappels': 'Recordatorios',
  'Repas du chat et ramassage': 'Comidas del gato y recogida de basura',
  'Repas chat': 'Comida del gato',
  'Poubelles': 'Basura',
  'Lave-vaisselle': 'Lavavajillas',
  'Tondeuse': 'Cortacésped',
  'Lavage': 'Lavado',
  'Rinçage': 'Aclarado',
  'Séchage': 'Secado',
  'Éteint': 'Apagado',
  'Allumé': 'Encendido',

  // Vue Piece
  '{n} % de luminosité': '{n} % de brillo',
  'En lecture': 'Reproduciendo',
  'Rien en lecture': 'Nada en reproducción',
  'Fermé': 'Cerrado',
  'Ouvert': 'Abierto',
  'Ouvert à {n} %': 'Abierto al {n} %',
  'Masquer les réglages': 'Ocultar ajustes',
  'Réglages de la vue': 'Ajustes de la vista',
  'Volet': 'Persiana',
  'actuel {n}°': 'ahora {n}°',
  'ARRÊT': 'APAGADO',
  'CONFORT': 'CONFORT',
  'FROID': 'FRÍO',
  'SEC': 'SECO',
  'VENTIL': 'VENT.',
  'Couleur': 'Color',
  'Fermer': 'Cerrar',
  'Ouvrir': 'Abrir',
  'Tout est éteint': 'Todo está apagado',
  'Appliquer {c}': 'Aplicar {c}',
  'Couleur {c}': 'Color {c}',

  // Vue Energie
  'réseau': 'red',
  'SURPLUS': 'EXCEDENTE',
  'PAS DE SURPLUS': 'SIN EXCEDENTE',
  'Autoconsommation': 'Autoconsumo',
  'Mode volets': 'Modo persianas',
  'Auto lever/coucher': 'Auto amanecer/anochecer',
  'Auto soleil': 'Auto sol',
  'Suit lever / coucher': 'Sigue amanecer / anochecer',
  '{n} ALLUMÉES': '{n} ENCENDIDAS',
  '{n} ALLUMÉE': '{n} ENCENDIDA',
  'Consommation': 'Consumo',
  'production solaire': 'producción solar',
  'Production solaire active': 'Producción solar activa',
  'Consommation réseau': 'Consumo de red',
  'Vente réseau': 'Venta a red',
  'Achat réseau': 'Compra de red',
  "Relevé temps réel du compteur et de l'onduleur": 'Lectura en tiempo real del contador y del inversor',
  '{n} % du 7 kVA souscrit': '{n} % de los 7 kVA contratados',
  'Injection vers le réseau': 'Inyección a la red',
  'Soutirage depuis le réseau': 'Consumo desde la red',
  'Importé': 'Importado',
  'Import inconnu': 'Importación desconocida',
  'Mois en cours': 'Mes en curso',
  'Journée en cours': 'Hoy hasta ahora',
  "Aujourd'hui": 'Hoy',

  // Vue Aspirateur
  'Démarrer le nettoyage': 'Iniciar limpieza',
  'Renvoyer au dock': 'Volver a la base',
  'Reprendre': 'Reanudar',
  'Mettre en pause': 'Pausar',
  'NETTOYAGE EN COURS': 'LIMPIANDO',
  'EN PAUSE': 'EN PAUSA',
  'SUR LA BASE': 'EN LA BASE',
  'AU REPOS': 'EN REPOSO',
  'Carte du logement': 'Mapa de la vivienda',
  'Base': 'Base',
  'Analyse de la carte…': 'Analizando el mapa…',

  // Vue Medias
  '{n} lecteurs': '{n} reproductores',
  '{n} lecteur': '{n} reproductor',
  'en lecture': 'reproduciendo',
  'au repos': 'en reposo',
  'Aucun média en cours sur ce lecteur': 'Nada en reproducción en este reproductor',
  'Autres lecteurs': 'Otros reproductores',
  'Aucun autre lecteur': 'Ningún otro reproductor',
  '{n} au repos sur {t}': '{n} en reposo de {t}',
  'Le service s’ouvre sur {nom} et la télécommande passe dessus.':
    'El servicio se abre en {nom} y el mando pasa a ese dispositivo.',
  'Lecture': 'Reproducir',
  'Lecture en cours': 'Reproduciendo ahora',
  'Lecteurs': 'Reproductores',
  'Au repos': 'En reposo',
  'volume {n} %': 'volumen {n} %',

  // Vue Securite
  'Surveillance': 'Vigilancia',
  'Alarme': 'Alarma',
  'Mouvement': 'Movimiento',
  'État inconnu': 'Estado desconocido',
  'Mouvement détecté': 'Movimiento detectado',
  'Tout est calme': 'Todo tranquilo',
  'CONNEXION ?': '¿CONEXIÓN?',
  'ALERTE': 'ALERTA',
  'ARMÉE · ABSENT': 'ARMADA · FUERA',
  'ARMÉE · PRÉSENT': 'ARMADA · EN CASA',
  'ARMÉE · NUIT': 'ARMADA · NOCHE',
  'SURVEILLÉE': 'VIGILADA',
  'activation en cours': 'armando',
  'déclenchée': 'activada',
  'état inconnu': 'estado desconocido',
  'armée · absent': 'armada · fuera',
  'armée · présent': 'armada · en casa',
  'armée · nuit': 'armada · noche',
  'désarmée': 'desarmada',
  'activation…': 'armando…',
  'inconnue': 'desconocida',
  'absent': 'fuera',
  'présent': 'en casa',
  'nuit': 'noche',
  'prête': 'lista',
  'Aucune caméra configurée': 'Ninguna cámara configurada',
  'Détection en cours sur une caméra': 'Detección en una cámara',
  'Toutes les zones sont calmes': 'Todas las zonas tranquilas',
  'Détecté': 'Detectado',
  'Aucun': 'Ninguno',
  'en ligne': 'en línea',
  '{noms} sont à la maison': '{noms} están en casa',
  '{noms} est à la maison': '{noms} está en casa',
  'Personne à la maison': 'Nadie en casa',
  '{n} présents': '{n} en casa',
  '{n} présent': '{n} en casa',
  'Personne': 'Nadie',
  'caméra': 'cámara',
  'caméras': 'cámaras',
  'personne à la maison': 'nadie en casa',
  'Activation en cours…': 'Armando…',
  'Intrusion détectée — vérifier immédiatement': 'Intrusión detectada — comprueba de inmediato',
  'État inconnu — connexion à vérifier': 'Estado desconocido — revisa la conexión',
  'Prête · tous les capteurs au repos': 'Lista · todos los sensores en reposo',
  'Surveillance totale active': 'Vigilancia total activa',
  'Mode nuit — périmètre et zones de repos': 'Modo noche — perímetro y zonas de descanso',

  // Vue Lumieres
  'Tout allumer': 'Encender todo',
  'Toutes': 'Todas',
  'Contrôle général': 'Control general',
  'Luminaires allumés': 'Luces encendidas',
  'Luminosité moyenne': 'Brillo medio',
  'Sur les luminaires allumés': 'Sobre las luces encendidas',

  // Vue Climat
  'Poêle': 'Estufa',
  'Poêle à granulés': 'Estufa de pellets',
  'Mode': 'Modo',
  'À L’ARRÊT': 'APAGADO',
  'Réglage détaillé en cliquant la carte de la zone': 'Ajuste detallado pulsando la tarjeta de la zona',
  'Réglable dans la barre ci-dessus': 'Ajustable en la barra de arriba',
  'À surveiller': 'A vigilar',
  'Zone': 'Zona',
  'Zones': 'Zonas',
  'Autres zones': 'Otras zonas',

  // Vue Volets
  'Vue d’ensemble de la position et du pilotage': 'Resumen de la posición y del control',
  'manuel': 'manual',

  // Vue Croquettes
  'Repas du jour': 'Comidas del día',
  'distribué': 'servido',
  'Repas du matin': 'Comida de la mañana',
  'Collation matinée': 'Tentempié de media mañana',
  'Collation après-midi': 'Tentempié de la tarde',
  'Repas du soir': 'Comida de la noche',

  // Vue Meteo
  'Au niveau de la mer': 'A nivel del mar',
  'Prévision 7 jours': 'Previsión a 7 días',
  'modéré': 'moderado',
  'Vent': 'Viento',
  'Pluie': 'Lluvia',
  'Protection conseillée au-delà de 6': 'Protección recomendada por encima de 6',
  'faible': 'bajo',
  'fort': 'alto',
  'très fort': 'muy alto',
  'extrême': 'extremo',
  'élevé': 'alto',
  'Ressenti': 'Sensación térmica',
  'Rafales': 'Rachas',
  'Pression': 'Presión',
  'Visibilité': 'Visibilidad',
  'Lever': 'Amanecer',
  'Coucher': 'Anochecer',
  'Indice UV': 'Índice UV',
  'Point de rosée': 'Punto de rocío',
  'Nuages': 'Nubes',
  'Vent {n} km/h': 'Viento {n} km/h',

  // Modes de climatisation
  'Arrêt': 'Apagado',
  'Confort': 'Confort',
  'Froid': 'Frío',
  'Sec': 'Seco',
  'Ventil': 'Vent.',
  'à l’arrêt': 'apagado',
  'aucune zone': 'ninguna zona',
  'confort': 'confort',
  'eco': 'eco',
  'horsgel': 'antihielo',

  // Vue Systeme
  'MÉMOIRE': 'MEMORIA',
  'Mémoire': 'Memoria',
  'Charge moyenne du CPU': 'Carga media de la CPU',
  'Partition de données': 'Partición de datos',
  'Température CPU': 'Temperatura de la CPU',
  "Seuil d'alerte à 75 °C": 'Umbral de alerta a 75 °C',
  'Détail affiché': 'Detalle mostrado',
  'Voir le détail': 'Ver el detalle',
  'À SURVEILLER': 'A VIGILAR',
  'il y a {n} h': 'hace {n} h',
  'il y a {n} s': 'hace {n} s',
  'il y a {n} min': 'hace {n} min',
  'relevé': 'lectura',
  '{n} machines en ligne': '{n} máquinas en línea',
  '{n} machine en ligne': '{n} máquina en línea',
  '{n} À SURVEILLER': '{n} A VIGILAR',
  'TOUT VA BIEN': 'TODO CORRECTO',
  'Disque /data': 'Disco /data',
  'RAM utilisée': 'RAM usada',
  'RAM du serveur': 'RAM del servidor',
  'Charge CPU': 'Carga de CPU',
  'mémoire': 'memoria',
  'Fonctionnement normal': 'Funcionamiento normal',
  'Ressources sous tension': 'Recursos al límite',
  'Serveur de stockage': 'Servidor de almacenamiento',
  'Processeur': 'Procesador',
  'Disque': 'Disco',
  'Stockage': 'Almacenamiento',

  // Compteurs a pluriel
  '{n} LAMPES ALLUMÉES': '{n} LUCES ENCENDIDAS',
  '{n} LAMPE ALLUMÉE': '{n} LUZ ENCENDIDA',
  '{n} volets': '{n} persianas',
  '{n} volet': '{n} persiana',
  '{n} volets suivis': '{n} persianas seguidas',
  '{n} volet suivi': '{n} persiana seguida',
  '{n} zones': '{n} zonas',
  '{n} zone': '{n} zona',
  '{n} zones ciblées': '{n} zonas seleccionadas',
  '{n} zone ciblée': '{n} zona seleccionada',
  'Position moyenne': 'Posición media',
  '{n} pièces détectées': '{n} áreas detectadas',
  '{n} pièce détectée': '{n} área detectada',
  'avec la consigne': 'respecto a la consigna',
  'Relevé de la zone': 'Lectura de la zona',
  'Écart de': 'Desviación de',
  'batterie': 'batería',

  // Ecran Entites — chauffage
  'Chauffage': 'Calefacción',
  'Un thermostat (climate.…) est trouvé tout seul : rien à saisir. Cette liste sert aux radiateurs fil pilote — un interrupteur entouré de ses aides, que rien ne permet de deviner.':
    'Un termostato (climate.…) se detecta solo: aquí no hay nada que introducir. Esta lista es para radiadores de hilo piloto: un interruptor rodeado de sus ayudas, que nada permite adivinar.',
  'Interrupteur': 'Interruptor',
  'Consigne': 'Consigna',
  'Auto': 'Auto',
  'Chambre': 'Dormitorio',

  // Parametres
  '{n} thèmes': '{n} temas',
  'actives sur {n}': 'activas de {n}',
  'Réglages propres à cet appareil': 'Ajustes propios de este dispositivo',
  '{n} profils': '{n} perfiles',
  '{n} MISES À JOUR': '{n} ACTUALIZACIONES',
  '{n} MISE À JOUR': '{n} ACTUALIZACIÓN',
  '{n} configurées': '{n} configuradas',
  '{n} entités configurées, toutes résolues': '{n} entidades configuradas, todas resueltas',
  'Toutes les entités configurées répondent': 'Todas las entidades configuradas responden',
  '{n} EN ATTENTE': '{n} PENDIENTES',
  'TOUT EST À JOUR': 'TODO ACTUALIZADO',
  'À JOUR': 'ACTUALIZADO',
  'THÈME': 'TEMA',
  'Connexion': 'Conexión',
  'Connexion HA': 'Conexión con HA',
  'toutes résolues': 'todas resueltas',
  'profils du foyer': 'perfiles del hogar',
  'réseau local': 'red local',
  'Vues': 'Vistas',
  'vues disponibles': 'vistas disponibles',
  'configurées': 'configuradas',
  'À propos': 'Acerca de',
  'version installée': 'versión instalada',
  'Utilisateurs': 'Usuarios',
  'Automatisations': 'Automatizaciones',
  'Apparence': 'Apariencia',

  // Etats d'aspirateur
  'Nettoyage': 'Limpiando',
  'Sur la base': 'En la base',
  'Sur base': 'En la base',
  'En pause': 'En pausa',
  'En veille': 'En espera',
  'Retour base': 'Volviendo a la base',
  'Erreur': 'Error',
  'Indisponible': 'No disponible',
  'Inconnu': 'Desconocido',
  'Inactif': 'Inactivo',
  "À la station d'accueil": 'En la base de carga',

  // Actions
  'Rafraîchir': 'Actualizar',
  'Redémarrer': 'Reiniciar',
  'Redémarrer HA': 'Reiniciar HA',
  'Exécuter': 'Ejecutar',
  'Exécuter maintenant': 'Ejecutar ahora',
  'Vérifier': 'Comprobar',
  'Terminé': 'Hecho',
  'Précédent': 'Anterior',
  'Répéter': 'Repetir',
  'Aléatoire': 'Aleatorio',
  'Couper le son': 'Silenciar',
  'Éteindre': 'Apagar',
  'Tout éteindre': 'Apagar todo',
  'Tout réafficher': 'Mostrar todo de nuevo',
  'Désarmer': 'Desarmar',
  'Rétablir': 'Restaurar',
  "Rétablir l'automatique": 'Restaurar el automático',
  'Rétablir les défauts': 'Restaurar valores por defecto',
  'Revenir à auto': 'Volver a automático',
  'Changer de thème': 'Cambiar de tema',
  'Appliquer une scène': 'Aplicar una escena',
  'Ouvrir les paramètres': 'Abrir los ajustes',
  "Retour à l'accueil": 'Volver al inicio',
  'Copier la config': 'Copiar la configuración',
  'Importer une config': 'Importar una configuración',
  'Enregistrer le code': 'Guardar el código',
  'Créer une vue': 'Crear una vista',
  'Réassocier les pièces': 'Volver a asociar las áreas',
  'Détecter automatiquement': 'Detectar automáticamente',
  'Lancer sur': 'Reproducir en',
  'Télécommande': 'Mando',
  'Pilotage à la main': 'Control manual',
  'Volet par volet': 'Persiana por persiana',
  'Afficher / masquer le menu': 'Mostrar / ocultar el menú',
  'Pivoter la carte d’un quart de tour': 'Girar el mapa un cuarto de vuelta',

  // Ajouts
  'Ajouter un appareil': 'Añadir un dispositivo',
  'Ajouter un lecteur': 'Añadir un reproductor',
  'Ajouter un poste': 'Añadir una emisora',
  'Ajouter un profil': 'Añadir un perfil',
  'Ajouter un thermostat': 'Añadir un termostato',
  'Ajouter un titre': 'Añadir un título',
  'Ajouter un volet': 'Añadir una persiana',
  'Ajouter une carte': 'Añadir una tarjeta',
  'Ajouter une lumière': 'Añadir una luz',

  // Recherche et filtres
  'Filtrer par nom…': 'Filtrar por nombre…',
  'Rechercher une entité (nom ou id)…': 'Buscar una entidad (nombre o id)…',
  'Rechercher une entité…': 'Buscar una entidad…',
  'Rechercher une pièce, une scène…': 'Buscar un área, una escena…',
  'Pièce, vue, scène…': 'Área, vista, escena…',
  'Toutes les sections': 'Todas las secciones',
  'Période': 'Periodo',
  'Vue complète': 'Vista completa',

  // Mesures
  'Température': 'Temperatura',
  'Humidité': 'Humedad',
  'Luminosité': 'Brillo',
  'Coût': 'Coste',
  'Coût estimé': 'Coste estimado',
  'État': 'Estado',
  'Prévision': 'Previsión',
  'Réservoir': 'Depósito',
  'Serpillière': 'Mopa',
  'Brosse latérale': 'Cepillo lateral',
  'Débit d’eau': 'Caudal de agua',
  'Présent': 'En casa',
  'Prénom': 'Nombre',
  'Nom affiché': 'Nombre mostrado',
  'À jour': 'Actualizado',
  'Masquées': 'Ocultas',
  'masquée': 'oculta',
  'météo': 'clima',
  'humidité du sol': 'humedad del suelo',

  // Titres de sections
  'APERÇU': 'RESUMEN',
  'CHAÎNE': 'CANAL',
  'ENTITÉ': 'ENTIDAD',
  'ENTITÉS': 'ENTIDADES',
  'ICÔNE': 'ICONO',
  'RÔLE': 'ROL',
  'VOUS': 'TÚ',
  'ZONES UTILISÉES': 'ÁREAS USADAS',
  'LUMIÈRES ALLUMÉES': 'LUCES ENCENDIDAS',
  "MASQUÉES POUR L'INSTANT": 'OCULTAS POR AHORA',
  'INTERVALLE DE RAFRAÎCHISSEMENT': 'INTERVALO DE ACTUALIZACIÓN',
  'INTÉRIEUR · HUMIDITÉ': 'INTERIOR · HUMEDAD',
  'TEMPÉRATURE · 24 H': 'TEMPERATURA · 24 H',
  'Activité · 24 h': 'Actividad · 24 h',
  'Maison · Temps réel': 'Casa · Tiempo real',
  'Bilan instantané': 'Balance instantáneo',
  'Journal système': 'Registro del sistema',
  'Mises à jour': 'Actualizaciones',
  'Entités': 'Entidades',
  'Entités suivies': 'Entidades seguidas',
  'Entités synchronisées': 'Entidades sincronizadas',
  'Entités du dashboard': 'Entidades del panel',
  'Entités de cette vue': 'Entidades de esta vista',
  'Aucune entité': 'Ninguna entidad',
  'Entité native': 'Entidad nativa',
  'Entité camera': 'entidad camera',
  'Entité person': 'entidad person',
  'Entité switch': 'entidad switch',
  'Lecteurs médias': 'Reproductores multimedia',
  'Caméras en direct': 'Cámaras en directo',
  'Caméras (Accueil)': 'Cámaras (Inicio)',
  'Pièces (Accueil)': 'Áreas (Inicio)',
  'Vos pièces': 'Tus áreas',
  'Appareils de la pièce': 'Dispositivos del área',
  'Collection de scènes': 'Colección de escenas',
  'Gestion des vues': 'Gestión de vistas',
  'Vues intégrées': 'Vistas integradas',
  'Vue personnalisée': 'Vista personalizada',
  'Menu latéral et vues perso': 'Menú lateral y vistas propias',
  'Liaison des capteurs': 'Vinculación de sensores',
  'Capteurs reliés aux cartes': 'Sensores vinculados a las tarjetas',
  'Zones ciblées': 'Zonas seleccionadas',
  'Zones à nettoyer': 'Zonas a limpiar',
  'Nettoyage ciblé': 'Limpieza selectiva',
  'Profil par défaut': 'Perfil por defecto',
  'Profil actif sur cet appareil — reconnu depuis la session Home Assistant':
    'Perfil activo en este dispositivo — reconocido desde la sesión de Home Assistant',
  'Communauté': 'Comunidad',
  'Hôte principal': 'Host principal',
  'Passerelle réseau': 'Puerta de enlace',
  'Sans token': 'Sin token',
  'Auto-hébergée, sans CDN': 'Autoalojada, sin CDN',
  'Interrupteurs traités comme lumières': 'Interruptores tratados como luces',
  'Synchronisation entre accès': 'Sincronización entre accesos',
  'Bascule automatique pour Nabu Casa': 'Cambio automático para Nabu Casa',
  'Proposer la bascule Nabu Casa': 'Ofrecer el cambio a Nabu Casa',
  'hors du réseau local': 'fuera de la red local',
  'Réseau local muet': 'Red local sin respuesta',
  "État de l'installation": 'Estado de la instalación',
  'État des appareils': 'Estado de los dispositivos',
  'État des mises à jour': 'Estado de las actualizaciones',
  'Tout est à jour': 'Todo está actualizado',
  'Dernière exécution': 'Última ejecución',
  'Dernière vérification': 'Última comprobación',
  'Depuis la mise en service': 'Desde la puesta en marcha',
  'Économie du jour': 'Ahorro del día',
  'Économie solaire': 'Ahorro solar',
  'Thème': 'Tema',
  'Thème actif': 'Tema activo',
  'Thème par défaut': 'Tema por defecto',
  'Thème, mode, effets': 'Tema, modo, efectos',
  'Matière & formes': 'Material y formas',
  'Matière des cartes': 'Material de las tarjetas',
  'Ombres portées': 'Sombras',
  'Liserés': 'Bordes finos',
  'Contraste renforcé': 'Contraste reforzado',
  'Effets animés': 'Efectos animados',
  'Effets météo animés': 'Efectos meteorológicos animados',
  'Mode édition': 'Modo edición',
  'Suivre le thème Home Assistant': 'Seguir el tema de Home Assistant',
  'Langue': 'Idioma',
  'Suivre HA': 'Seguir a HA',
  'Suivre Home Assistant': 'Seguir a Home Assistant',

  // Themes
  'A plat, sans ombre': 'Plano, sin sombra',
  'Verre dépoli, flou': 'Vidrio esmerilado, difuminado',
  'Néon nocturne': 'Neón nocturno',
  'Material épuré': 'Material depurado',
  'Océan Material': 'Océano Material',
  'Sobre, façon GitHub': 'Sobrio, estilo GitHub',
  'Prune, rose poudré': 'Ciruela, rosa empolvado',
  'Ambiance fête': 'Ambiente de fiesta',

  // Phrases d'aide
  'Appliqué au thème choisi.': 'Se aplica al tema elegido.',
  'Aucun appareil détecté pour cette pièce.': 'Ningún dispositivo detectado en esta área.',
  'Pas de capteur configuré pour cette pièce.': 'Ningún sensor configurado para esta área.',
  'Toutes les pièces configurées sont déjà associées.': 'Todas las áreas configuradas ya están asociadas.',
  'Aucune vue personnalisée. « + Nouvelle vue » pour commencer.':
    'Ninguna vista personalizada. «+ Nueva vista» para empezar.',
  'Aucune entité météo dans Home Assistant. Cette vue n’a rien à afficher.':
    'Ninguna entidad de clima en Home Assistant. Esta vista no tiene nada que mostrar.',
  'Prévision horaire indisponible pour cette entité.': 'Previsión horaria no disponible para esta entidad.',
  'Prévision journalière indisponible pour cette entité.': 'Previsión diaria no disponible para esta entidad.',
  'Vue vide — active le crayon (en haut) pour ajouter des cartes.':
    'Vista vacía — usa el lápiz (arriba) para añadir tarjetas.',
  "Chaque entité choisie s'ajoute immédiatement à la vue.":
    'Cada entidad elegida se añade a la vista al instante.',
  "Coche pour ajouter, décoche pour retirer. Les modifications s'appliquent tout de suite.":
    'Marca para añadir, desmarca para quitar. Los cambios se aplican al instante.',
  "Les modifications s'appliquent immédiatement à cet appareil":
    'Los cambios se aplican al instante en este dispositivo',
  'Retire (×), réordonne (‹ ›) ou ajoute des cartes. Quitte avec le crayon du haut.':
    'Quita (×), reordena (‹ ›) o añade tarjetas. Sal con el lápiz de arriba.',
  'Crée tes propres vues avec tes entités — elles apparaissent dans le menu latéral.':
    'Crea tus propias vistas con tus entidades — aparecen en el menú lateral.',
  'Créées avec tes entités, éditables à tout moment': 'Creadas con tus entidades, editables en cualquier momento',
  'Ce qui apparaît dans le menu latéral, et ce que tu as créé toi-même':
    'Lo que aparece en el menú lateral, y lo que has creado tú',
  'Gérées dans Home Assistant': 'Gestionadas en Home Assistant',
  'Les automatisations restent créées et modifiées dans Home Assistant':
    'Las automatizaciones se siguen creando y editando en Home Assistant',
  'Autocomplétion en tapant. « Enregistrer » recharge le dashboard pour appliquer.':
    'Autocompletado al escribir. «Guardar» recarga el panel para aplicar.',
  'Une entité vide masque simplement la donnée sur les cartes concernées':
    'Una entidad vacía simplemente oculta ese dato en las tarjetas afectadas',
  'Plus court = plus de requêtes vers Home Assistant.':
    'Más corto = más peticiones a Home Assistant.',
  'Calque le thème actif de Home Assistant et désactive les choix ci-dessous.':
    'Copia el tema activo de Home Assistant y desactiva las opciones de abajo.',
  'Thème suivi depuis Home Assistant — coupe « Suivre » pour choisir manuellement.':
    'Tema seguido desde Home Assistant — desactiva «Seguir» para elegir a mano.',
  'Le verre rend les cartes translucides et floute ce qui passe dessous.':
    'El vidrio vuelve translúcidas las tarjetas y difumina lo que pasa por debajo.',
  'Détache les cartes du fond. À couper pour un rendu plat.':
    'Separa las tarjetas del fondo. Desactívalo para un aspecto plano.',
  'Trait de 1 px autour des cartes et des tableaux.': 'Línea de 1 px alrededor de tarjetas y tablas.',
  'Rayon des cartes, des champs et des boutons.': 'Radio de tarjetas, campos y botones.',
  'Éclaircit les textes secondaires et marque les séparateurs.':
    'Aclara los textos secundarios y refuerza los separadores.',
  'Éléments actifs, jauges et liens.': 'Elementos activos, indicadores y enlaces.',
  "l'aperçu suit le thème choisi": 'la vista previa sigue el tema elegido',
  'Seul un administrateur peut ajouter, modifier ou supprimer un utilisateur.':
    'Solo un administrador puede añadir, editar o eliminar un usuario.',
  'Requis pour basculer vers un profil Admin. Reste local à cet appareil (jamais synchronisé).':
    'Necesario para cambiar a un perfil de administrador. Se queda en este dispositivo (nunca se sincroniza).',
  'Requis pour ce profil': 'Necesario para este perfil',
  'Ce que le profil affiche sous son nom': 'Lo que el perfil muestra bajo su nombre',
  'Ce que le robot fait pendant son passage': 'Lo que hace el robot durante su pasada',
  'Totaux tenus par le robot': 'Totales que lleva el robot',
  'Signalée par le robot': 'Indicado por el robot',
  'Surface parcourue et durée du dernier passage': 'Superficie recorrida y duración de la última pasada',
  'Sur la carte ou dans la liste — laisse vide pour un passage complet':
    'En el mapa o en la lista — déjalo vacío para una pasada completa',
  'Quantité d’eau envoyée à la serpillière': 'Cantidad de agua enviada a la mopa',
  'Suit le passage du robot. Choisis la caméra dans Paramètres → Entités.':
    'Sigue la pasada del robot. Elige la cámara en Ajustes → Entidades.',
  'Usure du tampon · à remplacer sous 20 %': 'Desgaste de la almohadilla · cambiar por debajo del 20 %',
  'Usure · révision sous 20 %': 'Desgaste · revisión por debajo del 20 %',
  'Usure · à changer sous 20 %': 'Desgaste · cambiar por debajo del 20 %',
  'Usure · à remplacer sous 20 %': 'Desgaste · reemplazar por debajo del 20 %',
  'RAS · véhicule présent': 'Sin novedad · vehículo presente',
  'Aérer au-delà de 1 000 ppm': 'Ventilar por encima de 1 000 ppm',
  'Courbes sur 24 h : température, humidité et CO₂':
    'Curvas de 24 h: temperatura, humedad y CO₂',
  'Température, humidité et CO₂ par pièce': 'Temperatura, humedad y CO₂ por área',
  'Détections caméra par heure, heure courante en vert':
    'Detecciones de cámara por hora, la hora actual en verde',
  'Compteur électrique · temps réel': 'Contador eléctrico · tiempo real',
  'Estimation du jour, production autoconsommée':
    'Estimación del día, producción autoconsumida',
  'Part de la production consommée sur place': 'Parte de la producción consumida in situ',
  'Part des automatisations activées': 'Parte de las automatizaciones activadas',
  'Automatisation déclenchée le plus récemment': 'Automatización activada más recientemente',
  'Modules suivis dont la version est la plus récente':
    'Complementos seguidos con la versión más reciente',
  'Relevé Home Assistant sur la période choisie':
    'Lectura de Home Assistant en el periodo elegido',
  'Relevés de l’entité météo': 'Lecturas de la entidad de clima',
  'Mesurée sur le dernier appel': 'Medido en la última llamada',
  'Adresse utilisée sur le réseau domestique': 'Dirección usada en la red doméstica',
  'Le capteur ne répond pas': 'El sensor no responde',
  'Connexion Home Assistant perdue — les données affichées peuvent être obsolètes':
    'Conexión con Home Assistant perdida — los datos mostrados pueden estar obsoletos',
  'Demande de rafraîchissement envoyée à Home Assistant':
    'Petición de actualización enviada a Home Assistant',
  'Une erreur est survenue pendant le rendu. Le détail ci-dessous permet de la corriger.':
    'Se ha producido un error al mostrar la vista. El detalle de abajo permite corregirlo.',
  'rien à afficher pour cette installation': 'nada que mostrar para esta instalación',
  'Aucun repas restant aujourd’hui': 'No queda ninguna comida hoy',
  'Aucune carte : désigne l’entité': 'Sin mapa: indica la entidad',
  'Relance le cœur sans toucher à la machine · ~40 s':
    'Reinicia el núcleo sin tocar la máquina · ~40 s',
  'Reboot complet de HAOS Nova · 2 à 3 min hors ligne':
    'Reinicio completo de HAOS Nova · 2 a 3 min sin conexión',
  'Arrêt complet · rallumage physique requis':
    'Apagado completo · hay que encenderlo físicamente',
  'Fermeture au crépuscule': 'Cierre al anochecer',
  "La scène s'applique au groupe de la pièce sélectionnée":
    'La escena se aplica al grupo del área seleccionada',
  'La télécommande n’apparaît que pour les téléviseurs. Choisis-en un pour la retrouver.':
    'El mando solo aparece para televisores. Elige uno para recuperarlo.',
  'pour ce lecteur : seules les commandes de lecture et de volume répondent.':
    'para este reproductor: solo responden los controles de reproducción y volumen.',
  'Sans équipement d’ambiance — réseau, énergie, serveurs. Rarement des pièces.':
    'Sin equipos de ambiente — red, energía, servidores. Rara vez áreas.',
  'Cliquer pour modifier · glisser pour déplacer (flèches ← →)':
    'Pulsa para editar · arrastra para mover (flechas ← →)',
  'Clique une zone « ? » pour la nommer': 'Pulsa una zona «?» para darle nombre',
  'Quelle pièce est-ce ?': '¿Qué área es esta?',
  'Mode édition : choisis le panneau d’alarme et les caméras de cette vue.':
    'Modo edición: elige el panel de alarma y las cámaras de esta vista.',
  'Mode édition : choisis l’entité météo de cette vue.':
    'Modo edición: elige la entidad de clima de esta vista.',
  'Mode édition : clique un volet pour le modifier, glisse-le pour le déplacer.':
    'Modo edición: pulsa una persiana para editarla, arrástrala para moverla.',
  'Mode édition : clique une zone pour la modifier, glisse-la pour la déplacer.':
    'Modo edición: pulsa una zona para editarla, arrástrala para moverla.',
  "Entité météo (vue Météo, bannière de l'Accueil, conseils extérieur).":
    'Entidad de clima (vista Clima, banner de Inicio, consejos de exterior).',
  "Panneau d'alarme (vue Sécurité, bannière, notifications).":
    'Panel de alarma (vista Seguridad, banner, notificaciones).',
  'Entités switch affichées dans la vue Lumières.':
    'entidades switch mostradas en la vista Luces.',
  'États des entités et réglages de cet appareil':
    'Estados de las entidades y ajustes de este dispositivo',
  'Tableau de bord domotique auto-hébergé pour Home Assistant':
    'Panel domótico autoalojado para Home Assistant',
  'React + Vite · servi par l’intégration': 'React + Vite · servido por la integración',
  "testées à l'enregistrement": 'comprobadas al guardar',
  'toutes (light.a, light.b)': 'todas (light.a, light.b)',
  'Accueil, Pièces, Scènes, Objets, Énergie, Sécurité, Système':
    'Inicio, Áreas, Escenas, Dispositivos, Energía, Seguridad, Sistema',
  'Lumières, Climat, Volets, Aspirateur, Croquettes, Médias':
    'Luces, Climatización, Persianas, Aspiradora, Pienso, Multimedia',
  'Présence, caméras, médias': 'Presencia, cámaras, multimedia',
  "C'est prêt": 'Listo',
  'Bon à savoir': 'Conviene saber',
  'Bon après-midi': 'Buenas tardes',
  // Seguridad, Sistema y varios
  'Absent': 'Ausente',
  'Alimentation': 'Alimentación',
  'Appareils connectés': 'Dispositivos conectados',
  'Aucun événement système sur 24 h.': 'Ningún evento del sistema en 24 h.',
  'Clients réseau': 'Clientes de red',
  'Colis livré': 'Paquete entregado',
  'Confirmer ?': '¿Confirmar?',
  'Deuxième machine': 'Segunda máquina',
  'En service': 'En servicio',
  'Entrée': 'Entrada',
  'Extérieur': 'Exterior',
  'Façade': 'Fachada',
  'Grappe de disques': 'Matriz de discos',
  'Historique': 'Historial',
  'Hors ligne': 'Sin conexión',
  'Journal indisponible sur cet accès.': 'Registro no disponible en este acceso.',
  'Les états et les commandes viennent de Home Assistant, dans toutes les langues qu’il connaît. Les noms de pièces et d’appareils aussi : ils ne sont pas traduits ici.': 'Los estados y los controles vienen de Home Assistant, en todos los idiomas que conoce. Los nombres de estancias y dispositivos también: no se traducen aquí.',
  'Machine hors ligne — dernier état inconnu.': 'Máquina sin conexión — último estado desconocido.',
  'Machines': 'Máquinas',
  'Mode nuit': 'Modo noche',
  'Mémoire à {n} %': 'Memoria al {n} %',
  'Mémoire élevée': 'Memoria alta',
  'Nuit': 'Noche',
  'Partition /data à {n} % — prévoir une purge de la base ou des sauvegardes.': 'Partición /data al {n} % — conviene purgar la base de datos o las copias de seguridad.',
  'Personne détectée': 'Persona detectada',
  'Pilotage courant': 'Control habitual',
  'Processeur à {c} et mémoire à {m} — débit du LAN encore nominal.': 'Procesador al {c} y memoria al {m} — el rendimiento de la LAN sigue siendo normal.',
  'Processeur à {c} et mémoire à {m} — vérifier les conteneurs actifs.': 'Procesador al {c} y memoria al {m} — revisar los contenedores activos.',
  'Périmètre surveillé': 'Perímetro vigilado',
  'RAM de la passerelle': 'RAM de la pasarela',
  'RAS': 'Sin novedad',
  'Redémarrage complet de la machine · 2 à 3 min hors ligne': 'Reinicio completo de la máquina · 2 a 3 min sin conexión',
  'Serveur Home Assistant': 'Servidor Home Assistant',
  'Sonnette': 'Timbre',
  'Stop': 'Parar',
  'Séjour': 'Salón',
  'Tous les systèmes opérationnels': 'Todos los sistemas operativos',
  'Troisième machine': 'Tercera máquina',
  'Véhicule présent': 'Vehículo presente',
  'alarme {etat}': 'alarma {etat}',
  'charge': 'carga',
  'historique indisponible': 'historial no disponible',
  'le cœur risque un redémarrage forcé': 'el núcleo podría reiniciarse a la fuerza',
  'non exposée': 'no expuesta',
  'non exposés': 'no expuestos',
  'processeur': 'procesador',
  '{n} appareils': '{n} dispositivos',
  '{n} caméra en ligne': '{n} cámara en línea',
  '{n} caméras en ligne': '{n} cámaras en línea',
  '{n} clients': '{n} clientes',
  '{n} h': '{n} h',
  '{n} j': '{n} d',
  '{n} présent sur {t}': '{n} de {t} en casa',
  '{n} présents sur {t}': '{n} de {t} en casa',
  '{n} système hors ligne': '{n} sistema sin conexión',
  '{n} systèmes hors ligne': '{n} sistemas sin conexión',
  '— le cœur risque un redémarrage forcé.': '— el núcleo podría reiniciarse a la fuerza.',
};
